### ISSUE TITLE
checkStatus() Method

### ISSUE THREAD

**Issue by upstate-online** [mbecker5/Comp-345-Team#11]
htd: returns/prints accurate status of animal

**Comment by mbecker5** [comment]
15 minutes on tests and 15 minutes on implementation.

**Comment by mbecker5** [comment]
Added a more thorough test and fixed minor bugs about 15/20 minutes

**Comment by mbecker5** [comment]
A demo for this would consist of currently running the test. In the future it would be good to change the status and see that it changes.(this might be better for set status though)
