### ISSUE TITLE
Construct Animal Object

### ISSUE THREAD

**Issue by vcrabtree** [mbecker5/Comp-345-Team#2]

**Comment by mbecker5** [comment]
An hour to make test and an hour to make class.

**Comment by mbecker5** [comment]
Test could be more thorough but I have some questions for the client and team before continuing.

**Comment by mbecker5** [comment]
added more test and very minor debugging maybe about 30/40 mins

**Comment by mbecker5** [comment]
The way to demo this would be to run the tests for now and see that they pass. I did add a few print statements so you can see whats going on a bit. There is only one animal object I am testing here and its the same for every test just for consistency. In the future Id like to add tests testing for other kinds of animals and more animals with varying information.
