### ISSUE TITLE
Implement validateCredentials()

### ISSUE THREAD

**Issue by AidanD-boot** [mbecker5/Comp-345-Team#31]

**Comment by vcrabtree** [comment]
**How to demo:** Tests will be made that create a manager account, test cases in which the password is incorrect, test cases in which the username does not exist, and test cases in which the username and password are both correct.

**What's Been Done**
- Wrote tests: 15 minutes
- Started method: 15 minutes
- Updated method to fit with current manager object setup: 20 minutes

**Still to Do**
- Create AccountDoesNotExistException
- Make ManagerTests file and move tests there
- Run to ensure all tests pass

**Comment by vcrabtree** [comment]
**What's Been Done**
- Created AccountDoesNotExistException: 10 minutes
- Integrated validateCredentials method with checkCredentialsMethod: 10 minutes

**Total Time Spend on Card:** 1 Hour 10 Minutes
