### ISSUE TITLE
Implement createAccount()

### ISSUE THREAD

**Issue by AidanD-boot** [mbecker5/Comp-345-Team#32]
How to demo: screen share showing the function test passed.

**Comment by mari707** [comment]
What's Been Done:

- [ ] Create an addManager test-10 minutes
Rule: Only one manager per store

- [ ] Created an employeeCollection class that will be used for managers, patrons, and volunteers(hashmap data structure)-15 minutes

- [ ] Created an addManager method -20 minutes

total time: 45 minutes
