### ISSUE TITLE
Implement remove method

### ISSUE THREAD

**Issue by mari707** [mbecker5/Comp-345-Team#38]

**Comment by mbecker5** [comment]
How to demo: Tests that show working to do list update method possible print of the whole list to show that its actually removed

**Comment by vcrabtree** [comment]
- 30 Minutes: Wrote tests for simple to do array list
- 45 Minutes: Wrote remove method and adjusted tests so they would pass
- 30 Minutes: Updated method and tests to account for to do list priority queue update
